Add variable definitions for chapter 7
iiasa/socdr-workflow pull request #4
Opened 2024-04-10 16:52 UTC by danielhuppmann

Adding the variables for chapter 7 based on the data received so far, with some minor spelling harmonizations. Please review the descriptions

2024-04-12 13:12 UTC, gidden requested changes
Thanks so much @danielhuppmann - I added some comments for update.

2024-04-12 13:12 UTC, gidden commented on definitions/variable/tag_land-removal.yaml
> +        description: land removal
all carbon removal on land, including both conventional CDR and removals due to indirect carbon fluxes aligned with national greenhouse gas inventories

2024-04-12 13:12 UTC, gidden commented on definitions/variable/tag_land-removal.yaml
> +    - Land|Direct:
`Land|Conventional CDR`

2024-04-12 13:12 UTC, gidden commented on definitions/variable/tag_land-removal.yaml
> +        description: direct land removal
conventional carbon removal on land excluding shifting cultivation

2024-04-12 13:12 UTC, gidden commented on definitions/variable/tag_land-removal.yaml
> +        description: indirect land removal
carbon removal on land due to indirect carbon fluxes accounted for in NGHGIs but not by scientific models

2024-04-12 13:12 UTC, gidden commented on definitions/variable/variables.yaml
> +- Carbon Removal [{Quarter-Percentile}]:
I do not see this defined anywhere in this PR, but want to confirm it is the sum of novel CDR and conventional CDR (conventional defined in land-removal)

2024-04-12 16:16 UTC, danielhuppmann commented on definitions/variable/tag_land-removal.yaml
> +        description: indirect land removal
Done

2024-04-12 16:17 UTC, danielhuppmann commented on definitions/variable/tag_land-removal.yaml
> +        description: land removal
Done

2024-04-12 16:19 UTC, danielhuppmann commented on definitions/variable/variables.yaml
> +- Carbon Removal [{Quarter-Percentile}]:
I don't see a variable like `Carbon Removal|Land` or subcategories of it in the provided data.

2024-04-12 18:26 UTC, gidden commented on definitions/variable/variables.yaml
> +- Carbon Removal [{Quarter-Percentile}]:
@gaurav-ganti - could you help check on this please?

2024-04-15 09:45 UTC, danielhuppmann commented
Chapter 7 was changed to Chapter 8

2024-04-15 13:19 UTC, gidden commented
Thanks again so much @danielhuppmann. In reviewing the data file you sent and what is in our figure data sheet, I have the following requests to variable names:

1. AR6 Reanalysis|OSCARv3.2|Carbon Removal|Land|Conventional CDR  -> Carbon Removal|Conventional
2. Gross Emissions|CO2 -> Gross Emission Reductions from 2020|CO2

2024-04-15 13:22 UTC, danielhuppmann commented
Thanks for the comments, @gidden. In the interest of readability, can I suggest an alternative?

> Gross Emissions|CO2 -> ~Gross Emission Reductions from 2020|CO2~ Gross Emissions|CO2 [Reductions relative to 2020]

2024-04-15 13:52 UTC, danielhuppmann commented
And to avoid any confusion, @gidden - should the variables
- *AR6 Reanalysis|OSCARv3.2|Carbon Removal|Land*
- *AR6 Reanalysis|OSCARv3.2|Carbon Removal|Land|Indirect*

also be shortened similar to your suggestion for *AR6 Reanalysis|OSCARv3.2|Carbon Removal|Land|Conventional CDR*?

2024-04-16 06:27 UTC, gidden commented
No I would prefer to keep those variables as is. They are relevant for Figure 7.4, but not for any indicator (they mix flux types which should not be misunderstood by users/policy makers).

2024-04-16 06:28 UTC, gidden commented on definitions/variable/variables.yaml
> +- Carbon Removal [{Quarter-Percentile}]:
Ok, I think this is clear now

2024-04-16 11:17 UTC, merged